### ISSUE TITLE
About Contact Information

### ISSUE THREAD

**Issue by Joaocoko** [zz4fap/scatter-phy#1]
Hi, I found your OFDM system code is really helpful, can i have your contact information to talk about this?

**Comment by zz4fap** [comment]
Hi, yes, sure. My email is ***@***.***

**Comment by Joaocoko** [comment]
Sorry how can I see you email, because it shows me ****

**Comment by zz4fap** [comment]
Sorry, I didn't know github suppresses email addresses. Let me try it
again: zz4fap at gmail dot com
replace at and dot by their respective characters.

**Comment by Joaocoko** [comment]
Cool, it is working now
